### ISSUE TITLE
Include HTML (Content-Type: text/html) in email destination.

### ISSUE THREAD

**Issue by Sampathreddygopireddy118** [opendistro-for-elasticsearch/alerting#323] opened 2020-12-10 14:38 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by skkosuri-amzn** [comment] 2020-12-15 03:46
Duplicate of #324

**Closed by skkosuri-amzn** 2020-12-15 03:46 UTC
