### ISSUE TITLE
[BUG] Unable to create monitor after upgrade to ODFE 1.11.0

### ISSUE THREAD

**Issue by fbarbeira** [opendistro-for-elasticsearch/alerting#293] opened 2020-11-06 11:25 UTC
**Describe the bug**
I tried to create a monitor with "admin" user and gets error "connection refused"

**To Reproduce**
1. Go to 'Create monitor'.
2. Try to create a single monitor using an index.
4. See error.

**Expected behavior**
The monitor should be created.

**Details**:

This is the error on the elasticsearch log:

```
[2020-11-06T12:12:55,424][ERROR][c.a.o.a.u.AlertingException] [data01] Alerting error: java.net.ConnectException: Connection refused
[2020-11-06T12:12:55,424][WARN ][r.suppressed             ] [data01] path: /_opendistro/_alerting/monitors, params: {pretty=true}
com.amazon.opendistroforelasticsearch.alerting.util.AlertingException: Connection refused
	at com.amazon.opendistroforelasticsearch.alerting.util.AlertingException$Companion.wrap(AlertingException.kt:80) ~[opendistro_alerting-1.11.0.1.jar:1.11.0.1]
	at com.amazon.opendistroforelasticsearch.alerting.transport.TransportIndexMonitorAction$IndexMonitorHandler$resolveUserAndStart$1.onFailure(TransportIndexMonitorAction.kt:196) [opendistro_alerting-1.11.0.1.jar:1.11.0.1]
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:617) [elasticsearch-rest-client-7.9.1.jar:7.9.1]
	at org.elasticsearch.client.RestClient$1.failed(RestClient.java:375) [elasticsearch-rest-client-7.9.1.jar:7.9.1]
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137) [httpcore-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionFailed(DefaultClientExchangeHandlerImpl.java:101) [httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:426) [httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:348) [httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62) [httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:392) [httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137) [httpcore-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$1.failed(PoolingNHttpClientConnectionManager.java:316) [httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137) [httpcore-4.4.12.jar:4.4.12]
	at org.apache.http.nio.pool.RouteSpecificPool.failed(RouteSpecificPool.java:162) [httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.nio.pool.AbstractNIOConnPool.requestFailed(AbstractNIOConnPool.java:609) [httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.failed(AbstractNIOConnPool.java:889) [httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.SessionRequestImpl.failed(SessionRequestImpl.java:162) [httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:176) [httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148) [httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351) [httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221) [httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) [httpasyncclient-4.1.4.jar:4.1.4]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.Exception: java.net.ConnectException: Connection refused
	... 23 more
```

I tried to create the example monitor of the [opendistro doc](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/api/#create-monitor) and gives the same error:

```
PUT /myindex

POST _opendistro/_alerting/monitors
{
  "type": "monitor",
  "name": "test-monitor",
  "enabled": true,
  "schedule": {
    "period": {
      "interval": 1,
      "unit": "MINUTES"
    }
  },
  "inputs": [{
    "search": {
      "indices": ["myindex"],
      "query": {
        "size": 0,
        "aggregations": {},
        "query": {
          "bool": {
            "filter": {
              "range": {
                "@timestamp": {
                  "gte": "||-1h",
                  "lte": "",
                  "format": "epoch_millis"
                }
              }
            }
          }
        }
      }
    }
  }]
}
```

Error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "alerting_exception",
        "reason" : "Connection refused"
      }
    ],
    "type" : "alerting_exception",
    "reason" : "Connection refused",
    "caused_by" : {
      "type" : "exception",
      "reason" : "java.net.ConnectException: Connection refused"
    }
  },
  "status" : 500
}
```

**Comment by brssgrg** [comment] 2020-11-06 12:43
Hi, I'm facing a same problem on a fresh 1.11.0 install.

**Comment by skkosuri-amzn** [comment] 2020-11-06 15:47
This is being discussed in : https://github.com/opendistro-for-elasticsearch/alerting/issues/292

**Comment by skkosuri-amzn** [comment] 2020-11-06 15:48
Closing this. Duplicate of https://github.com/opendistro-for-elasticsearch/alerting/issues/292

**Closed by skkosuri-amzn** 2020-11-06 15:48 UTC
Labels: bug
