### ISSUE TITLE
Alerting trigger variables  are empty

### ISSUE THREAD

**Issue by artemNN** [opendistro-for-elasticsearch/alerting#176] opened 2020-03-13 14:51 UTC
I use custom webhook in Alerting.
I use the variables {{ctx.monitor.schedule.period.interval}} and {{ctx.monitor.schedule.period.unit}} in the message constructor.
In "Message preview" they work and returned current values, but are not sent via webhook. They are empty.

**Comment by DandyDeveloper** [comment] 2020-03-30 03:06
I'm actually experiencing the same thing in 1.4.0 (and 1.2.0) but with the Slack integration... Something must have happened in the ES 7.X migration, because I am no longer about to use variables under `ctx.results`. I can use them in the preview but it looks like the rendering of the document in the client is having problems: 

Example trigger: 
```
{{ #ctx.results }} 
{{ hits.total.value }} Blahblah: [{{ #aggregations.2.buckets }} {{ key }}, {{ /aggregations.2.buckets }}]

{{ #aggregations.2.buckets }} 
Node: {{ key }}
  {{ #3.buckets }}
      - {{ key }}
  {{ /3.buckets }}
{{ /aggregations.2.buckets }}
{{ /ctx.results }}
```

Output in preview: 

```
66 Blahblah: [ Node 1, Node 2, ]

Node: Node 1
      - Error Blah
Node: Node 2
      - Error 2
      - Error 1
```

Output when the alert is triggered:
```
 Disk Issues Found
 
Disk errors found in node: [ , ]

Node:
 
     -
```

**Comment by DandyDeveloper** [comment] 2020-03-30 03:08
@lucaswin-amzn Hey Lucas, I don't know who else is supposed to be active here but this seems like a huge issue. Any chance we can get some eyes on it?

**Comment by DandyDeveloper** [comment] 2020-03-30 03:09
@dbbaughe If you're around as well. Please help!

**Comment by dbbaughe** [comment] 2020-03-30 04:18
Hi @artemNN and @DandyDeveloper,

Unfortunately the message preview in the Kibana plugin is a best guess effort of what is available. The calculation of the context is done during runtime and the message preview just fills in the root level namespace objects. That means it's also showing way more than what's really available. We should definitely clean this up to at least show the correct variables.

As a note, you can refer to documentation here to see what is available: https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/monitors/#available-variables

I don't believe `{{ctx.monitor.schedule.period.interval}} and {{ctx.monitor.schedule.period.unit}}` were ever though.

We should be returning the results though, so @DandyDeveloper could you provide a sample query/response? Thanks

**Comment by DandyDeveloper** [comment] 2020-03-30 04:35
@dbbaughe I spent a little more time on my issue, it's actually the templating logic that is weird... 

Basically, my template was: 

```
{{ #ctx.results }} 
{{ hits.total.value }} Blahblah: [{{ #aggregations.2.buckets }} {{ key }}, {{ /aggregations.2.buckets }}]

{{ #aggregations.2.buckets }} 
Node: {{ key }}
  {{ #3.buckets }}
      - {{ key }}
  {{ /3.buckets }}
{{ /aggregations.2.buckets }}
{{ /ctx.results }}
```

Rendered perfectly in the preview. HOWEVER, send a bunch of blanks to my destination. 

I then realised that the actual issue is how the vars are encapsulated: 

```
{{ctx.results.0.hits.total.value}} Blahblah: [{{#aggregations.2.buckets}} {{key}}, {{/aggregations.2.buckets}}]

{{ #aggregations.2.buckets}} 
Node: {{key}}
  {{#3.buckets}}
      - {{key}}
  {{/3.buckets}}
{{/aggregations.2.buckets}}
{{/ctx.results}}
```

Notice the subtle difference? No spaces between the `{{` and `}}`. **That was literally it.**

Looks like when we render with Mustache in FE, we might take this into consideration, but the HTML templating engine doesn't? 

It was really as simple as that.

**Comment by DandyDeveloper** [comment] 2020-03-30 04:36
@artemNN You might want to see my response above, you may fine that this solves your problem.

**Comment by ftianli-amzn** [comment] 2020-11-05 07:56
I could reproduce the issue for an arbitrary monitor.
Besides, I did a bit more testing on it:
when typing`{{ctx.monitor}}` in the "Message" text area, I can only receive 
```
{_id=, _version=1, name=test monitor, enabled=false}
```
in the test message received, which means only `version`, `name` and `enabled` is accessible from the `monitor` object.

**Comment by alisagao511** [comment] 2021-01-08 19:21
You can't separate  {{ #ctx.results }} {{ #aggregations.2.buckets }}. You need use them in a row.  
You can try to test as below if your variables output is empty in Destination but you can see them and returned current values in "Message preview".

This is my  query response:

` "hits": {
        "hits": [],
        "total": 26,
        "max_score": 0
    },
    "took": 19,
    "timed_out": false,
    "aggregations": {
        "group_by_hosts": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 3,
            "buckets": [
                {
                    "doc_count": 4,
                    "exception_type": {
                        "hits": {
                            "hits": [
                                {
                                    "_index": "tomcat-castro-log-2021-01-08",
                                    "_type": "tomcat-castro-log",
                                    "_source": {
                                        "jvm": "prfo01b",
                                        "exceptionType": "HttpException",
                                        "host": "foapp01",
                                        "message": "XXXXXXXX"
                                    },
                                    "_id": "XXXXXXXXX",
                                    "_score": 11.562773
                                }
                            ],
                            "total": 4,
                            "max_score": 11.562773
                        }
                    },
                    "key": "prfo01b"
                },
                {
                    "doc_count": 4,
                    "exception_type": {
                        "hits": {
                            "hits": [
                                {
                                    "_index": "tomcat-castro-log-2021-01-08",
                                    "_type": "tomcat-castro-log",
                                    "_source": {
                                        "jvm": "prfo13b",
                                        "exceptionType": "NullPointerException",
                                        "host": "foapp13",
                                        "message": "XXXXXXXXX"
                                    },
                                    "_id": "XXXXXXXX",
                                    "_score": 11.562773
                                }
                            ],
                            "total": 4,
                            "max_score": 11.562773
                        }
                    },
                    "key": "prfo13b"
                },`



I use the following variables in the Message:

`- Message:
{{#ctx.results.0.aggregations.group_by_hosts.buckets}}
  * Host: {{exception_type.hits.hits.0._source.host}}
    JVM: {{exception_type.hits.hits.0._source.jvm}}
    ExceptionType: {{exception_type.hits.hits.0._source.exceptionType}}
    Num exceptions: {{doc_count}}
{{/ctx.results.0.aggregations.group_by_hosts.buckets}}`

I can see the current values for these variables in "Message preview". And I triggered an test alert message, I can see the alert message shown the current values for these variables.

![image](https://user-images.githubusercontent.com/68913564/104055218-60859200-51bc-11eb-8089-28bfa53a5d88.png)

Received this event via the events API
{
  "details": "Test message.
The number of Exceptions is 28 in 30m. Alerts just entered alert status. Please investigate the issue.
Please refer to: https:////  for details.
- Trigger: Alarm: Test message
- Severity: 1
- Total FO Exceptions: 28
- Period start: 2021-01-08T19:12:40.236Z
- Period end: 2021-01-08T19:13:40.236Z
- Error: 
- Message:
  * Host: app08
    JVM: prfo08b
    ExceptionType: NullPointerException
    Num exceptions: 4
  * Host: app15
    JVM: prfo15b
    ExceptionType: ParseException
    Num exceptions: 4
  * Host: app14
    JVM: prfo14a
    ExceptionType: IllegalArgumentException
    Num exceptions: 3
  * Host: app01
    JVM: prfo01b
    ExceptionType: HttpException
    Num exceptions: 2
  * Host: app05
    JVM: prfo05b
    ExceptionType: ParseException
    Num exceptions: 2

**Comment by qreshi** [comment] 2022-02-18 15:19
Closing in favor of https://github.com/opensearch-project/alerting/issues/57

**Closed by qreshi** 2022-02-18 15:19 UTC
Labels: bug
