### ISSUE TITLE
Alerts not reflecting on dashboard

### ISSUE THREAD

**Issue by BlueRedTeam** [opendistro-for-elasticsearch/alerting#10] opened 2019-03-22 06:26 UTC
as of now alerts function is not working like SIEM alerts or real time alerts.  expectation is alerts should show on dashboard or notify on each and every condition match irrespective of whether it is active or acknowledge or completed. If condition matching two time then two alerts should be on dashboard , not only one

**Comment by elfisher** [comment] 2019-03-22 15:39
@BlueRedTeam, it sounds the main feedback is that each trigger match should be logged during an active alerting event. For example within an active alerting event, you want it to log each occurrence of a trigger match. Would supporting something like that address your concern? 

The acknowledge function was built so that once someone is working on resolving the issue they can acknowledge and notifications will not continue to be resent on every trigger match for that event.

**Comment by BlueRedTeam** [comment] 2019-03-28 17:36
Yes

**Comment by elfisher** [comment] 2019-04-03 23:32
This looks like a duplicate of the [per document request](https://github.com/opendistro-for-elasticsearch/alerting/issues/13). I'm closing and linking to the other issue.

**Closed by elfisher** 2019-04-03 23:32 UTC
