### ISSUE TITLE
provide HTML support for Alerting email notifications 

### ISSUE THREAD

**Issue by anjanaasok** [opendistro-for-elasticsearch/alerting#325] opened 2020-12-14 07:23 UTC
Currently only plain/text is supported in notification email body. Looking for HTML support.

**Comment by skkosuri-amzn** [comment] 2020-12-15 03:44
This is duplicate of https://github.com/opendistro-for-elasticsearch/alerting/issues/324. Closing this and using #324 to track the process of this enhancement.

**Closed by skkosuri-amzn** 2020-12-15 03:44 UTC
